language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

matrix:
  allow_failures:
    - php: 8.0
    - php: nightly

before_script:
  - php -S localhost:8000 -t fixtures/ &> /dev/null &
  - composer self-update
  - composer install --prefer-source

script:
  - vendor/bin/php-cs-fixer fix --config=.php_cs -v --dry-run .
  - vendor/bin/phpstan analyse src -c phpstan.neon
  - vendor/bin/phpunit
